In [1]:
import numpy as np 

In [45]:
def generate_logistic_data(theta,n,m):
    beta = np.random.randn(m + 1)# generate random numbers from normal distribution(mean = 0, std = 1)
    X_random = np.random.randn(n, m)
    ones = np.ones((n, 1))
    X = np.hstack((ones, X_random))
    z = np.dot(X, beta)
    p = 1 / (1 + np.exp(-z))
    Y = (p > 0.5).astype(int)
    flip = np.random.binomial(1, theta, n)
    Y = np.abs(Y - flip)
    Y = Y.reshape(-1, 1)
    return X, Y, beta

In [51]:
theta = 0.2   # 20% noise
n = 100       # 100 samples
m = 3         # 3 independent variables

X, Y, beta = generate_logistic_data(theta, n, m)

print("X shape:", X.shape) # X → input matrix
print("Y shape:", Y.shape) # Y → binary labels (output)
print("Beta:", beta) # true coefficients

X shape: (100, 4)
Y shape: (100, 1)
Beta: [ 1.55117566  2.08362688  0.40562002 -1.01865159]


In [21]:
beta = np.random.randn(3 + 1) # m+1 cuz intercept is included 
print(beta)# β=[β0,β1,β2,β3]
# β₀ → intercept
# β₁, β₂, β₃ → feature weights

[-0.56234582  0.70410257  1.69687548 -1.44212926]


In [11]:
X_random = np.random.randn(2, 3)
print(X_random)

[[ 1.56011731 -0.30109986  1.53785797]
 [ 1.32959176  0.15334804  0.48261649]]


In [15]:
ones = np.ones((2, 1))
print(ones)

[[1.]
 [1.]]


In [17]:
X = np.hstack((ones, X_random))# hstack joins horizontally
print(X)

[[ 1.          1.56011731 -0.30109986  1.53785797]
 [ 1.          1.32959176  0.15334804  0.48261649]]


In [23]:
z = np.dot(X, beta) # zi​=β0​+β1​x1​+β2​x2​+...
print(z) # Shape = (n,)

[-2.19258216 -0.06195968]


In [25]:
p = 1 / (1 + np.exp(-z))
print(p)# output probability between 0 and 1 

[0.10041859 0.48451503]


In [29]:
Y = (p > 0.5).astype(int) # .astype(int) boolean ko 0/1 me convert karta hai.
print(Y)

[0 0]


In [37]:
flip = np.random.binomial(1, 0.2, 2) # Probability of success = theta and n trials 
print(flip)

[0 0]


In [41]:
Y = np.abs(Y - flip)
print(Y)

[0 0]


In [43]:
Y = Y.reshape(-1, 1)
print(Y)

[[0]
 [0]]
